# Generated by Django 5.0.3 on 2024-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='color',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
